name: Сообщить о проблеме
description: Опишите проблему с принтером подробно. Перед созданием отчета обратитесь к боту.
title: "Проблема: "
labels: ["bug"]
assignees: ["ghzserg"]
body:
  - type: markdown
    attributes:
      value: |
        **Перед тем, как задавать вопрос, спросите его у [@zmod_help_bot](http://t.me/zmod_help_bot) и прочитайте:**
        - **[Алгоритм оформления TAR_CONFIG](https://github.com/ghzserg/zmod/wiki/Help)** - без него тикет рассматриваться не будет
        - [FAQ](https://github.com/ghzserg/zmod/wiki/FAQ)
        - [Рекомендации](https://github.com/ghzserg/zmod/wiki/Recomendations)
        - [Документацию по макросам](https://github.com/ghzserg/zmod/wiki/Macros)
        - [AD5X](https://github.com/ghzserg/zmod/wiki/AD5X)

        **Важно:** Если вы используете какие-либо плагины кроме recommend, то отключите их.
        Если проблема вызвана плагином g28_tenz или nopoop, укажите это в заголовке.
        [Если ошибка в плагине bambufy, обратитесь к автору](https://github.com/function3d/bambufy).

        **Одна проблема, один тикет** - не добавляйте в один тикет несколько проблем, решена будет только одна.

  - type: dropdown
    id: printer_model
    attributes:
      label: Модель принтера
      description: Выберите вашу модель
      multiple: false
      options:
        - AD5M
        - AD5M PRO
        - AD5X
    validations:
      required: true

  - type: dropdown
    id: display_type
    attributes:
      label: Тип экрана/интерфейса
      description: Как вы работаете с принтером?
      options:
        - Я работаю с родным экраном
        - Я работаю с Guppyscreen
        - Я работаю без экрана
    validations:
      required: true

  - type: dropdown
    id: firmware_type
    attributes:
      label: Версия Klipper
      description: Какую версию Klipper вы используете?
      options:
        - Я работаю с родным Klipper
        - Я работаю с Klipper 13
    validations:
      required: true

  - type: dropdown
    id: web_type
    attributes:
      label: Веб интерфейс
      description: Какой веб интерфейс вы используете?
      options:
        - Fluidd
        - Mainsail
    validations:
      required: true

  - type: textarea
    id: start_gcode
    attributes:
      label: Стартовый G-код
      description: Вставьте ваш стартовый G-код
      placeholder: |
        START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]
        M190 S[bed_temperature_initial_layer_single]
        M104 S[nozzle_temperature_initial_layer]
    validations:
      required: true

  - type: textarea
    id: end_gcode
    attributes:
      label: Завершающий G-код
      description: Вставьте ваш завершающий G-код
      placeholder: |
        END_PRINT
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: Подробное описание ошибки
      description: Максимально подробно опишите, что вы делали, что планировали получить и что получили.
      placeholder: |
        1. Шаг 1...
        2. Шаг 2...
        3. Ожидаемый результат...
        4. Фактический результат...
    validations:
      required: true

  - type: textarea
    id: config_attachment
    attributes:
      label: Прикрепите файл config-*.tar.gz
      description: |
        **ВАЖНО:** Без файла `config-*.tar.gz` тикет будет автоматически закрыт.
        1. Нажмите на область текстового поля ниже.
        2. Либо перетащите файл `config-*.tar.gz` прямо на эту область, либо используйте значок скрепки в углу поля для его выбора.
        3. В поле появится ссылка на загруженный файл. Убедитесь, что она есть.
      placeholder: "Перетащите файл сюда или нажмите, чтобы выбрать..."
    validations:
      required: false

  - type: textarea
    id: config_gcode
    attributes:
      label: Прикрепите GCODE файл
      description: |
        Прикрепите, при необходисомти файл при печати которого происходит сбой. Его лучше запаковать в zip архив.
        1. Нажмите на область текстового поля ниже.
        2. Либо перетащите GCODE файл прямо на эту область, либо используйте значок скрепки в углу поля для его выбора.
        3. В поле появится ссылка на загруженный файл. Убедитесь, что она есть.
      placeholder: "Перетащите файл сюда или нажмите, чтобы выбрать..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Проверьте перед отправкой:**
        - Я прикрепил файл `config-*.tar.gz`
        - Я отключил все сторонние плагины (кроме recommend)
        - Я прочитал рекомендованные материалы
        - **Одна проблема, один тикет** - не добавляйте в один тикет несколько проблем, решена будет только одна.